In [2]:
import pandas as pd

df = pd.read_csv("orders.csv")
print(df)

    OrderID      CustomerName                Product     Category  Quantity  \
0      1001        John Smith                 Laptop  Electronics         1   
1      1002         Sarah Lee             Headphones  Electronics         2   
2      1003          Ali Khan           Office Chair    Furniture         1   
3      1004        Alice Wong              Desk Lamp    Furniture         3   
4      1005     Carlos Mendez               Keyboard  Electronics         2   
5      1006      Nora Ibrahim               Notebook   Stationery         5   
6      1007       Emily Davis          Standing Desk    Furniture         1   
7      1008        James Park                Monitor  Electronics         2   
8      1009       Maria Rossi                    Pen   Stationery        10   
9      1010  Takeshi Nakamura                  Mouse  Electronics         1   
10     1011     Sophie Martin                 Webcam  Electronics         1   
11     1012         Raj Patel           File Cabinet

In [3]:
df.head()

OrderID   CustomerName       Product     Category  Quantity   Price  \
0     1001     John Smith        Laptop  Electronics         1  1200.0   
1     1002      Sarah Lee    Headphones  Electronics         2   150.0   
2     1003       Ali Khan  Office Chair    Furniture         1   300.0   
3     1004     Alice Wong     Desk Lamp    Furniture         3    45.0   
4     1005  Carlos Mendez      Keyboard  Electronics         2    80.0   

    OrderDate Shipped    Country  
0  2024-06-01     Yes        USA  
1  2024-06-03      No     Canada  
2  2024-06-04     Yes        UAE  
3  2024-06-05     Yes  Singapore  
4  2024-06-06      No     Mexico

In [8]:
df.columns

Index(['OrderID', 'CustomerName', 'Product', 'Category', 'Quantity', 'Price',
       'OrderDate', 'Shipped', 'Country'],
      dtype='object')

In [14]:
df[["Country","Product","Shipped"]]

Country                Product Shipped
0            USA                 Laptop     Yes
1         Canada             Headphones      No
2            UAE           Office Chair     Yes
3      Singapore              Desk Lamp     Yes
4         Mexico               Keyboard      No
5            UAE               Notebook     Yes
6             UK          Standing Desk     Yes
7    South Korea                Monitor      No
8          Italy                    Pen     Yes
9          Japan                  Mouse     Yes
10        France                 Webcam     Yes
11         India           File Cabinet      No
12     Australia                Stapler     Yes
13         Spain              USB Drive     Yes
14         China              Bookshelf      No
15         Egypt          Printer Paper     Yes
16        Poland         Wireless Mouse     Yes
17           USA         Desk Organizer      No
18         Japan             Calculator     Yes
19  Saudi Arabia             Whiteboard     Yes
20        Canada           Highlighters      No
21        Brazil      Bluetooth Speaker     Yes
22       Germany           Office Plant     Yes
23      Pakistan           Sticky Notes      No
24        Sweden           Tablet Stand     Yes
25        France         Paper Shredder     Yes
26     Argentina         Desk Chair Mat      No
27        Russia           Binder Clips     Yes
28   South Korea      Wireless Keyboard     Yes
29         Italy          Desk Calendar      No
30       Morocco                USB Hub     Yes
31       Germany       Document Scanner     Yes
32      Colombia  Desk Drawer Organizer      No
33           USA            Index Cards     Yes
34         Japan          Monitor Stand     Yes
35            UK     Desk Lamp with USB      No
36      Portugal       Wireless Earbuds     Yes
37          Iran               Desk Pad     Yes
38   South Korea            Power Strip      No
39       Ukraine             Desk Clock     Yes

In [16]:
df.iloc[39]

OrderID                 1040
CustomerName    Anna Ivanova
Product           Desk Clock
Category           Furniture
Quantity                   1
Price                   35.0
OrderDate         2024-07-11
Shipped                  Yes
Country              Ukraine
Name: 39, dtype: object

In [29]:
df[(df["Category"] == "Furniture") & (df["Country"] == "Uk")]

Empty DataFrame
Columns: [OrderID, CustomerName, Product, Category, Quantity, Price, OrderDate, Shipped, Country]
Index: []

In [31]:
import sys, site
print(sys.executable)
print(site.getusersitepackages())


c:\Users\15047\Desktop\dhshark\venv\Scripts\python.exe
C:\Users\15047\AppData\Roaming\Python\Python312\site-packages


In [2]:
import torch

print("Torch version:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("CUDA used by PyTorch:", torch.version.cuda)
print("GPU:", torch.cuda.get_device_name(0))


Torch version: 2.7.1+cu118
CUDA available: True
CUDA used by PyTorch: 11.8
GPU: NVIDIA GeForce RTX 3060 Laptop GPU


In [6]:
import torch

shape = (2,3)

ones = torch.ones(shape)
zeros = torch.zeros(shape)
random = torch.randn(shape)

print(ones)
print(zeros)
print(random)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[ 0.5285,  0.4216,  0.7993],
        [-0.6020, -0.9218,  0.4371]])


In [11]:
import torch

template = torch.tensor([[[1,2],[3,4]]])

tensor = torch.randn_like(template, dtype=torch.float)

print(tensor.shape)
print(tensor.dtype)
print(tensor.device)

torch.Size([1, 2, 2])
torch.float32
cpu


In [14]:
import torch 

x = torch.tensor([[1,2,3], [4,5,6]])

print(x.shape)
print (x.sum(dim=0))
print (x.sum(dim=1))

torch.Size([2, 3])
tensor([5, 7, 9])
tensor([ 6, 15])


In [3]:
import torch 

data = torch.tensor([[15,20,30,16],
                     [20,21,30,44],
                     [51,26,30,11]])

indices = torch.tensor([[0],[1],[1]])

selected_values = torch.gather(data,dim=0,index=indices)
print(selected_values)

tensor([[15],
        [20],
        [20]])


In [ ]:
import torch
import torch.nn as nn 
from sklearn.model_selection import train_test_split
import numpy as np 
import pandas as pd

class Model(nn.Module):
    def __init__(self, in_features=4,h1=8,h2=9, out_features=3):
        super().__init__()
        self.fc1=  nn.Linear(in_features,h1)
        self.fc2 = nn.Linear(h1,h2)
        self.output = nn.Linear(h2,out_features)

    def forward(self,x):
        x = torch.relu(self.fc1(x))
        x= torch.relu(self.fc2(x))
        x= self.output(x)

        return x
    
torch.manual_seed(44)
model = Model()



df = pd.read_csv("Iris.csv")
df = df.drop(columns=["Id"], errors="ignore")

df["Species"] = df["Species"].replace({
    "Iris-setosa": 0,
    "Iris-versicolor": 1,
    "Iris-virginica": 2
}).astype(int)

#train test spit set x y 

X= df.drop('Species', axis=1)
y = df['Species']
X = X.values
y = y.values

X_train,X_test, y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=41)
X_train = torch.FloatTensor(X_train)
X_test = torch.FloatTensor(X_test)

y_train = torch.LongTensor(y_train)
y_test = torch.LongTensor(y_test)

#criteria to measure error 
criterion = nn.CrossEntropyLoss()
#adam optimizer, learning rate = lr (epochs)
optimizer = torch.optim.Adam(model.parameters(), lr=0.01)

#train our model
epochs = 100
losses = []

for i in range(epochs):
    y_pred = model(X_train) #get predicted result
    #measure loss
    loss = criterion(y_pred,y_train)
    #keep track of losses 
    losses.append(loss.item())

    #print every 10 epoch
    if i % 10 ==0:
        print(f"epoch: {i} and loss : {loss}")

        #back propagation
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()


epoch: 0 and loss : 1.2354300022125244
epoch: 10 and loss : 0.8982402682304382
epoch: 20 and loss : 0.6109587550163269
epoch: 30 and loss : 0.4415954649448395
epoch: 40 and loss : 0.3440301716327667
epoch: 50 and loss : 0.2527320086956024
epoch: 60 and loss : 0.1664941906929016
epoch: 70 and loss : 0.10658339411020279
epoch: 80 and loss : 0.07356038689613342
epoch: 90 and loss : 0.05639585480093956


C:\Users\15047\AppData\Local\Temp\ipykernel_12452\2518649281.py:29: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["Species"] = df["Species"].replace({


In [ ]:
#evaluate model

model.eval()
class_names = ["setosa", "versicolor", "virginica"]

with torch.no_grad():
    for i in range(len(X_test)):
        logits = model(X_test[i].unsqueeze(0))
        pred = torch.argmax(logits, dim=1).item()
        true = y_test[i].item()
        print(f"{i+1:02d}. Pred: {class_names[pred]} | True: {class_names[true]}")



01. Pred: virginica | True: virginica
02. Pred: virginica | True: virginica
03. Pred: virginica | True: virginica
04. Pred: versicolor | True: versicolor
05. Pred: virginica | True: virginica
06. Pred: versicolor | True: versicolor
07. Pred: virginica | True: virginica
08. Pred: versicolor | True: versicolor
09. Pred: virginica | True: virginica
10. Pred: virginica | True: virginica
11. Pred: virginica | True: virginica
12. Pred: setosa | True: setosa
13. Pred: setosa | True: setosa
14. Pred: versicolor | True: versicolor
15. Pred: setosa | True: setosa
16. Pred: virginica | True: virginica
17. Pred: setosa | True: setosa
18. Pred: virginica | True: versicolor
19. Pred: setosa | True: setosa
20. Pred: setosa | True: setosa
21. Pred: versicolor | True: versicolor
22. Pred: virginica | True: virginica
23. Pred: setosa | True: setosa
24. Pred: setosa | True: setosa
25. Pred: versicolor | True: versicolor
26. Pred: versicolor | True: versicolor
27. Pred: versicolor | True: versicolor
28. P

: 